version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_DB: grovestreet_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  springboot-app:
    build:
      context: .  # Asume que el Dockerfile está en la raíz del proyecto
      dockerfile: Dockerfile
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/grovestreet_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
