version: "3.8"

services:
  # Servicio para la base de datos PostgreSQL
  postgres:
    image: postgres:latest
    container_name: grovestreet_db
    environment:
      POSTGRES_DB: grovestreet_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
